### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by jacopotediosi** [GiacomoDevIT/AntiDDoS#1]
The whole antiddos.php code is included in if(!$_COOKIE['challenge']) {}, therefore it is possible to bypass the system by creating a cookie with the name 'challenge' and value 'true'.

**Comment by GiacomoDevIT** [comment]
🤣.

**Comment by jacopotediosi** [comment]
It is completely unprofessional of you to close an issue without giving reasons.
Is this a wontfix?
