### ISSUE TITLE
The developer is bugged as much as the code if not more

### ISSUE THREAD

**Issue by cosoimmaginario** [GiacomoDevIT/AntiDDoS#5]
The title says everything.

**Steps to reproduce**
- Visit https://github.com/GiacomoDevIT/AntiDDoS/

A possible fix is to remove the lines from 0 to 90 of file `antiddos.php`.

**Comment by GiacomoDevIT** [comment]
hahaha so ridiculous

**Comment by cosoimmaginario** [comment]
Yes, you are right. And it's funny because it's true.
